# Generated by Django 2.2.5 on 2019-12-01 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitations',
            field=models.ManyToManyField(related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
