# Generated by Django 2.2.5 on 2019-10-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(verbose_name='Capacidad del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha en que termina el evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora en que termina el evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_full_day',
            field=models.BooleanField(default=False, verbose_name='El evento no tiene un horario definido'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='El evento es recurrente'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(verbose_name='Fecha en que comienza el evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora en que comienza el evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Titulo del evento'),
        ),
    ]
