# Generated by Django 2.2.5 on 2019-12-02 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_event_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='staff',
            field=models.ManyToManyField(related_name='staff_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
