# Generated by Django 2.2.5 on 2019-10-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20191021_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='picture',
            new_name='image',
        ),
    ]
