# Generated by Django 2.2.5 on 2019-10-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20191021_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='Ciudad Universitaria', max_length=100, verbose_name='Dirección del evento'),
        ),
    ]
