# Generated by Django 2.2.5 on 2019-12-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_invitations'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='event_history',
            field=models.ManyToManyField(to='events.Event'),
        ),
    ]
