# Generated by Django 2.2.5 on 2019-10-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_unam_community',
            field=models.BooleanField(default=True, verbose_name='unam_community status'),
        ),
    ]
