# Generated by Django 2.2.5 on 2019-12-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff_event',
            field=models.BooleanField(default=False, verbose_name='staff_event status'),
        ),
    ]
