# Generated by Django 2.2.5 on 2019-11-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_unam_community',
            field=models.BooleanField(default=True, verbose_name='unam_community status'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
