# Generated by Django 2.2.5 on 2019-09-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicentity',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
