# Generated by Django 2.2.5 on 2019-12-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191202_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='event_history',
            field=models.ManyToManyField(blank=True, null=True, to='events.Event'),
        ),
    ]
