# Generated by Django 2.2.5 on 2019-11-11 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191111_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='academic_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.AcademicEntity'),
        ),
    ]
