# Generated by Django 2.2.5 on 2019-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191202_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='event_history',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
