# Generated by Django 2.2.5 on 2019-11-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191111_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_host_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_unam_community',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
