# Generated by Django 2.2.5 on 2019-12-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191202_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_unam_community',
            field=models.BooleanField(default=False, verbose_name='unam_community status'),
        ),
    ]
